apiVersion: v2
name: caaas

description: A Helm chart for deploying CAAAS
type: application

version: 0.1.0
appVersion: "0.1.0"

sources:
  - https://github.com/bitnami/charts/tree/master/bitnami/postgresql

dependencies:
  - name: postgresql
    version: 10.16.2
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.enabled
