apiVersion: v2
name: caaas
description: A Helm chart for deploying CAAAS
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: "14.0.0"
    repository: "oci://registry-1.docker.io/bitnamicharts/postgresql"
