# File: configs/api.config.yaml
# This file is used to configure the API service in the Docker environment.

# HTTP server port
port: 8080

# Database migration
revision: 2
admin_key: "secret_admin_key"

# Database connection settings
storage:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "password"
  database: "postgres"
  ssl: "disable"

# Initial data for the API
urls:
  - shortened_id: "Google"
    address: "https://www.google.com"
    description: "Search Engine"
  - shortened_id: "Facebook"
    address: "https://www.facebook.com"
    description: "Social Media"
  - shortened_id: "Twitter"
    address: "https://www.twitter.com"
    description: "Microblogging Platform"
  - shortened_id: "GitHub"
    address: "https://www.github.com"
    description: "Code Hosting Platform"
  - shortened_id: "Stack Overflow"
    address: "https://www.stackoverflow.com"
    description: "Programming Q&A Site"
  - shortened_id: "Reddit"
    address: "https://www.reddit.com"
    description: "Social News Aggregation"
  - shortened_id: "LinkedIn"
    address: "https://www.linkedin.com"
    description: "Professional Networking"
  - shortened_id: "YouTube"
    address: "https://www.youtube.com"
    description: "Video Sharing Platform"
  - shortened_id: "Wikipedia"
    address: "https://www.wikipedia.org"
    description: "Online Encyclopedia"
  - shortened_id: "Amazon"
    address: "https://www.amazon.com"
    description: "E-commerce Platform"
  - shortened_id: "eBay"
    address: "https://www.ebay.com"
    description: "Online Auction Site"
  - shortened_id: "Netflix"
    address: "https://www.netflix.com"
    description: "Streaming Service"
