port: 8080
revision: 1
admin_key: "secret_admin_key"
storage:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "password"
  database: "postgres"
  ssl: "disable"
urls:
  - name: "Google"
    url: "https://www.google.com"
    description: "Search Engine"
  - name: "Facebook"
    url: "https://www.facebook.com"
    description: "Social Media"
  - name: "Twitter"
    url: "https://www.twitter.com"
    description: "Microblogging Platform"
  - name: "GitHub"
    url: "https://www.github.com"
    description: "Code Hosting Platform"
  - name: "Stack Overflow"
    url: "https://www.stackoverflow.com"
    description: "Programming Q&A Site"
  - name: "Reddit"
    url: "https://www.reddit.com"
    description: "Social News Aggregation"
  - name: "LinkedIn"
    url: "https://www.linkedin.com"
    description: "Professional Networking"
  - name: "YouTube"
    url: "https://www.youtube.com"
    description: "Video Sharing Platform"
  - name: "Wikipedia"
    url: "https://www.wikipedia.org"
    description: "Online Encyclopedia"
  - name: "Amazon"
    url: "https://www.amazon.com"
    description: "E-commerce Platform"
  - name: "eBay"
    url: "https://www.ebay.com"
    description: "Online Auction Site"
  - name: "Netflix"
    url: "https://www.netflix.com"
    description: "Streaming Service"
