---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "caaas.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{ toYaml .Values.caaas.labels | default "{}" }}
spec:
  type: {{ .Values.caaas.service.type }}
  ports:
    - port: {{ .Values.caaas.service.port }}
      targetPort: {{ .Values.caaas.service.port }}
      protocol: TCP
      name: http
  selector:
    caaas.application.type: api
    {{ toYaml .Values.caaas.labels | default "{}" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "caaas.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{ toYaml .Values.caaas.labels | default "{}" }}
spec:
  type: {{ .Values.caaas.service.type }}
  ports:
    - port: {{ .Values.caaas.service.port }}
      targetPort: {{ .Values.caaas.service.port }}
      protocol: TCP
      name: http
  selector:
    caaas.application.type: gateway
    {{ toYaml .Values.caaas.labels | default "{}" }}
